# Generated by Django 4.2.5 on 2023-09-25 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atordiretor',
            name='nacionalidade',
        ),
        migrations.AddField(
            model_name='atordiretor',
            name='nacionalidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
            preserve_default=False,
        ),
    ]
